//go:gernerate swag init
package server

import (
	"context"
	"fmt"
	"io"
	"io/ioutil"
	"net"
	"net/http"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/chennqqi/godnslog/cache"
	"github.com/chennqqi/godnslog/internal/auth"
	"github.com/chennqqi/godnslog/internal/demo"
	"github.com/chennqqi/godnslog/internal/ha"
	"github.com/chennqqi/godnslog/internal/interaction/fingerprint"
	"github.com/chennqqi/godnslog/internal/listener"
	v2models "github.com/chennqqi/godnslog/internal/models"
	"github.com/chennqqi/godnslog/internal/tlsmanager"
	"github.com/chennqqi/godnslog/internal/workflow"
	"github.com/chennqqi/godnslog/models"
	_ "github.com/chennqqi/godnslog/server/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gin-contrib/static"
	"github.com/gin-gonic/gin"
	"github.com/go-sql-driver/mysql"
	"github.com/hashicorp/go-retryablehttp"
	redis "github.com/redis/go-redis/v9"
	"github.com/sirupsen/logrus"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "modernc.org/sqlite"
	"xorm.io/xorm"
)

type WebServerConfig struct {
	Driver    string
	Dsn       string
	Domain    string
	IP        string
	Listen    string
	Swagger   bool
	WithGuest bool
	TestMode  bool

	// RedisAddr is an optional Redis address for HA session sharing.
	// If empty, MCP sessions use in-memory storage.
	RedisAddr string

	AuthExpire                   time.Duration
	DefaultCleanInterval         int64
	DefaultQueryApiMaxItem       int
	DefaultMaxCallbackErrorCount int64
	DefaultLanguage              string
	AnonymousMode                bool `json:"anonymous_mode"` // when true, don't record real source IPs

	// GeoIP configuration. MMDBPath is the location of GeoLite2-ASN.mmdb.
	// LicenseKey enables auto-download when the file is missing.
	GeoIPMMDBPath   string
	GeoIPLicenseKey string

	CaptchaEnabled bool          `json:"captcha_enabled"` // default true
	CaptchaExpire  time.Duration // default 2min

	// TLS configuration for standalone deployment mode.
	// When TLSMode is not "disabled", the server uses HTTPS.
	TLSMode     string
	TLSCertFile string
	TLSKeyFile  string
	ACMEEmail   string
	CertDir     string

	// Demo mode configuration.
	// When DemoMode is true, demo users and sample data are created.
	DemoMode       bool
	DemoResetHours int
}

type WebServer struct {
	WebServerConfig

	engine        *gin.Engine
	orm           *xorm.Engine
	store         *cache.Cache
	authService   *auth.Service
	workflowQueue *workflow.Queue
	workflowSvc   *workflow.Service

	uiMutex sync.Mutex

	//internal
	s             *http.Server
	client        *http.Client
	storeQuit     chan struct{}
	wg            sync.WaitGroup
	verifyKey     string //random generate
	listenerMgr   *listener.Manager
	haSvc         *ha.Service
	haNodeID      string
	haCancel      context.CancelFunc
	redisClient   *redis.Client
	fingerprinter *fingerprint.Fingerprinter
	captchaSvc    *captchaService
	tlsManager    *tlsmanager.Manager
	demoMgr       *demo.Manager
}

func NewWebServer(cfg *WebServerConfig, store *cache.Cache) (*WebServer, error) {
	app := &WebServer{}
	app.WebServerConfig = *cfg

	orm, err := xorm.NewEngine(cfg.Driver, cfg.Dsn)
	if err != nil {
		return nil, err
	}
	err = orm.Ping()
	if err != nil {
		return nil, err
	}
	app.orm = orm
	app.store = store

	// Initialize auth service
	app.authService = auth.NewService(orm)

	err = app.initDatabase()
	if err != nil {
		logrus.Errorf("[webserver.go::NewWebServer] initDatabase: %v", err)
		return nil, err
	}

	app.verifyKey = genRandomString(16)
	app.storeQuit = make(chan struct{})

	// Initialize GeoIP fingerprinter
	if cfg.GeoIPMMDBPath != "" {
		if err := fingerprint.EnsureMMDB(cfg.GeoIPMMDBPath, cfg.GeoIPLicenseKey); err != nil {
			logrus.Warnf("[webserver] GeoIP disabled: %v", err)
		}
		app.fingerprinter = fingerprint.NewFingerprinter(cfg.GeoIPMMDBPath)
		logrus.Infof("[webserver] GeoIP fingerprinter initialized (mmdb=%s)", cfg.GeoIPMMDBPath)
	} else {
		logrus.Info("[webserver] GeoIP disabled (no mmdb path configured)")
	}

	// Initialize captcha service
	if cfg.CaptchaEnabled {
		captchaExpire := cfg.CaptchaExpire
		if captchaExpire <= 0 {
			captchaExpire = 2 * time.Minute
		}
		app.captchaSvc = newCaptchaService(app.store, captchaExpire)
		logrus.Infof("[webserver.go::NewWebServer] captcha service initialized (expire=%v)", captchaExpire)
	} else {
		logrus.Info("[webserver.go::NewWebServer] captcha disabled")
	}

	// Initialize TLS manager
	if cfg.TLSMode != "" && cfg.TLSMode != "disabled" {
		mode, err := tlsmanager.ParseMode(cfg.TLSMode)
		if err != nil {
			logrus.Warnf("[webserver] invalid TLS mode %q: %v, falling back to disabled", cfg.TLSMode, err)
		} else {
			tlsMgr, err := tlsmanager.NewManager(tlsmanager.Config{
				Mode:      mode,
				Domain:    cfg.Domain,
				ACMEEmail: cfg.ACMEEmail,
				CertDir:   cfg.CertDir,
				CertFile:  cfg.TLSCertFile,
				KeyFile:   cfg.TLSKeyFile,
			})
			if err != nil {
				logrus.Warnf("[webserver] TLS manager init failed: %v, falling back to plain HTTP", err)
			} else {
				app.tlsManager = tlsMgr
				if tlsMgr.IsTLSEnabled() {
					logrus.Info("[webserver] TLS enabled")
				}
			}
		}
	}

	// Initialize demo mode
	if cfg.DemoMode {
		demoCfg := demo.DefaultConfig(cfg.Domain)
		if cfg.DemoResetHours > 0 {
			demoCfg.ResetInterval = time.Duration(cfg.DemoResetHours) * time.Hour
		}
		app.demoMgr = demo.NewManager(app.orm, demoCfg)
		if err := app.demoMgr.InitSeedData(); err != nil {
			logrus.Warnf("[webserver] demo seed data init failed: %v", err)
		}
		app.demoMgr.StartResetLoop()
		logrus.Info("[webserver] demo mode enabled")
	}

	return app, nil
}

func (self *WebServer) doClean() {
	cache := self.store
	session := self.orm.NewSession()
	defer session.Close()

	var ids []int64
	err := session.Table(&models.TblUser{}).Cols("id").Find(&ids)
	if err != nil {
		logrus.Errorf("[webserver.go::doClean] orm.Find: %v", err)
		return
	}
	now := time.Now()
	driver := self.orm.DriverName()
	if driver == "sqlite3" || driver == "sqlite" {
		now = now.Local()
	}

	for _, id := range ids {
		userKey := fmt.Sprintf("%v.user", id)
		v, exist := cache.Get(userKey)
		if exist {
			user := v.(*models.TblUser)
			t := now.Add(time.Duration(-1) * time.Duration(user.CleanInterval) * time.Second)
			session.Where(`uid=?`, id).And(`ctime<?`, t).Delete(&models.TblDns{})
			session.Where(`uid=?`, id).And(`ctime<?`, t).Delete(&models.TblHttp{})
		}
	}
}

func (self *WebServer) RunStoreRoutine() {
	store := self.store
	session := self.orm.NewSession()
	defer session.Close()
	ticker := time.NewTicker(1800 * time.Second)
	defer ticker.Stop()

	var client = retryablehttp.NewClient()
	client.RetryMax = 3
	client.RetryWaitMin = 5 * time.Second
	client.RetryWaitMax = 60 * time.Second

	dnsCallBack := func(rcd *DnsRecord) {
		defer self.wg.Done()
		req, err := retryablehttp.NewRequest("POST", rcd.Callback, nil)
		resp, err := client.Do(req)
		errorCountKey := fmt.Sprintf("%v.errcount", rcd.Uid)
		if err != nil {
			store.IncrementInt64(errorCountKey, 1)
			logrus.Infof("[webserver.go::RunStoreRoutine] dns callback: %v", err)
			return
		}
		store.Delete(errorCountKey)
		io.Copy(ioutil.Discard, resp.Body)
		resp.Body.Close()
	}

	// httpCallBack := func(rcd *HttpRecord) {
	// 	defer self.wg.Done()
	// 	req, err := retryablehttp.NewRequest("POST", rcd.Callback, nil)
	// 	resp, err := client.Do(req)
	// 	if err != nil {
	// 		logrus.Infof("[webserver.go::RunStoreRoutine] http callback:", err)
	// 		return
	// 	}
	// 	io.Copy(ioutil.Discard, resp.Body)
	// 	resp.Body.Close()
	// }

FOR_LOOP:
	for {
		select {
		case <-ticker.C:
			self.wg.Add(1)
			go func() {
				defer self.wg.Done()
				self.doClean()
			}()

		case rcd, ok := <-store.Output():
			if !ok {
				break FOR_LOOP
			}
			switch rcd.(type) {
			case *DnsRecord:
				d := rcd.(*DnsRecord)
				dnsRecord := &models.TblDns{
					Uid:    d.Uid,
					Domain: d.Domain,
					Var:    d.Var,
					Ip:     d.Ip,
					Ctime:  d.Ctime,
				}
				_, err := session.InsertOne(dnsRecord)
				if err != nil {
					logrus.Fatalf("[web.go::storeRoutine] orm.InsertOne: %v", err)
				}
				// Dual-write to unified interactions table with attribution
				interaction := v2models.FromTblDnsWithAttribution(dnsRecord, self.orm)
				// Override DNSType with actual query type from DNS server
				if d.Qtype != "" {
					interaction.DNSType = &d.Qtype
				}
				if _, err2 := session.InsertOne(interaction); err2 != nil {
					logrus.Errorf("[web.go::storeRoutine] dual-write interactions: %v", err2)
				}
				// Trigger matching workflows asynchronously
				self.triggerWorkflows(interaction)
				if d.Callback != "" && d.Uid > 0 {
					errorCountKey := fmt.Sprintf("%v.errcount", d.Uid)
					v, exist := store.Get(errorCountKey)
					if exist {
						if v.(int64) >= self.DefaultMaxCallbackErrorCount {
							break
						}
					}
					self.wg.Add(1)
					go dnsCallBack(d)
				}
			case *HttpRecord:
				// logged in `record` function
				// 	h := rcd.(*HttpRecord)
				// 	_, err := session.InsertOne(&models.TblHttp{
				// 		Uid:    h.Uid,
				// 		Url:    h.Url,
				// 		Ip:     h.Ip,
				// 		Ua:     h.Ua,
				// 		Data:   h.Data,
				// 		Ctype:  h.Ctype,
				// 		Method: h.Method,
				// 		Ctime:  h.Ctime,
				// 	})

				// 	if err != nil {
				// 		logrus.Fatalf("[web.go::storeRoutine] orm.InsertOne: %v", err)
				// 	}

				// 	//async callback
				// 	if h.Callback != "" && h.Uid > 0 {
				// 		self.wg.Add(1)
				// 		go httpCallBack(h)
				// 	}
			}
		}
	}
	close(self.storeQuit)
}

func (self *WebServer) Run() error {
	r := gin.New()
	r.Use(gin.Recovery())
	r.Use(gin.Logger())

	// CORS middleware - must be first
	r.Use(func(c *gin.Context) {
		c.Writer.Header().Set("Access-Control-Allow-Origin", "*")
		c.Writer.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(http.StatusOK)
			return
		}

		c.Next()
	})

	// Swagger UI (interactive API documentation)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	//static handler
	r.Use(static.Serve("/", static.LocalFile("dist", false)))
	r.NoRoute(func(c *gin.Context) {
		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(http.StatusOK)
			return
		}
		c.File("dist/index.html")
	})

	//api handler
	api := r.Group("/api")

	//auth group
	auth := api.Group("auth")
	{
		auth.POST("/login", self.userLogin)
		auth.POST("/logout", self.authHandler, self.userLogout)
		auth.GET("/info", self.authHandler, self.userInfo)
		auth.GET("/nav", self.authHandler, self.userNav)
		auth.GET("/captcha", self.getCaptcha)
	}

	// Register v2 API
	self.registerV2API(r)

	// Initialize Redis client for HA session sharing if configured
	if len(self.RedisAddr) > 0 {
		self.redisClient = redis.NewClient(&redis.Options{Addr: self.RedisAddr})
		if err := self.redisClient.Ping(context.Background()).Err(); err != nil {
			logrus.Warnf("[webserver.go::Run] Redis ping failed, falling back to in-memory sessions: %v", err)
			self.redisClient = nil
		} else {
			logrus.Info("[webserver.go::Run] Redis client connected for MCP session sharing")
		}
	}

	// Initialize workflow service and async action queue
	self.workflowSvc = workflow.NewService(self.orm)
	ctx := context.Background()
	self.workflowQueue = workflow.NewQueue(ctx, self.workflowSvc, 3, 3, self.orm)
	self.workflowQueue.Start()
	logrus.Info("[webserver.go::Run] workflow async queue started with 3 workers")

	// Initialize WebSocket hub for real-time push
	initWS()

	// Start listener manager
	listenerStore := listener.NewXormStore(self.orm)
	self.listenerMgr = listener.NewManager(listenerStore, logrus.StandardLogger())
	if err := self.listenerMgr.Start(context.Background()); err != nil {
		logrus.Errorf("[webserver.go::Run] failed to start listener manager: %v", err)
	}

	// Initialize HA service and register current node
	self.initHA()

	//data group
	data := api.Group("/record", self.authHandler)
	{
		data.GET("/dns", self.getDnsRecord)
		data.GET("/http", self.getHttpRecord)
		data.DELETE("/dns", self.delDnsRecord)
		data.DELETE("/http", self.delHttpRecord)
	}

	// WebSocket endpoint (auth required)
	api.GET("/ws", self.authHandler, wsHandler)

	setting := api.Group("/setting", self.authHandler)
	{
		setting.GET("/app", self.getAppSetting)
		setting.POST("/app", self.setAppSetting)

		setting.GET("/security", self.getSecuritySetting)
		setting.POST("/security", self.setSecuritySetting)

		setting.GET("/resolve", self.getResolveRecord)
		setting.POST("/resolve", self.setResolveRecord)
		setting.DELETE("/resolve", self.delResolveRecord)
	}

	//admin
	admin := api.Group("admin", self.authHandler, self.verifyAdminPermission)
	{
		admin.DELETE("/user", self.delUser)
		admin.PUT("/user", self.addUser)
		admin.POST("/user", self.setUser)
		admin.GET("/user/list", self.userList)
	}

	//record handler
	dataApi := r.Group("/data", self.dataPreHandler, self.dataAuthHandler)
	{
		dataApi.GET("/dns", self.queryDnsRecord)
		dataApi.GET("/http", self.queryHttpRecord)
	}
	//http log
	r.Any("/log/:shortId/*any", self.record)

	payload := r.Group("/payload")
	{
		payload.GET("/xss", self.xss)
		payload.GET("/phprfi", self.phpRFI)
	}

	s := &http.Server{
		Handler: r,
	}
	l, err := net.Listen("tcp", self.Listen)
	if err != nil {
		return err
	}
	self.s = s

	// Use TLS if TLS manager is configured and enabled
	if self.tlsManager != nil && self.tlsManager.IsTLSEnabled() {
		s.TLSConfig = self.tlsManager.TLSConfig()
		logrus.Infof("[webserver.go::Run] HTTPS server starting on %s", self.Listen)
		return s.ServeTLS(l, "", "")
	}

	logrus.Infof("[webserver.go::Run] HTTP server starting on %s", self.Listen)
	return s.Serve(l)
}

func (self *WebServer) Shutdown(ctx context.Context) error {
	var err error
	if self.listenerMgr != nil {
		self.listenerMgr.Stop()
	}
	if self.demoMgr != nil {
		self.demoMgr.Stop()
	}
	self.shutdownHA()
	if self.redisClient != nil {
		self.redisClient.Close()
	}
	if self.s != nil {
		err = self.s.Shutdown(ctx)
	}
	// Stop accepting new WebSocket connections and drain active clients.
	stopWS(ctx)
	//important: stop input then call shutdown

	<-self.storeQuit
	self.orm.Close()
	return err
}

// initHA initializes the HA service, registers the current node, and starts a heartbeat goroutine.
func (self *WebServer) initHA() {
	store := ha.NewXormStore(self.orm)
	self.haSvc = ha.NewService(store)

	// Generate a unique node ID based on hostname and listen address
	hostname, _ := os.Hostname()
	if hostname == "" {
		hostname = "node"
	}
	self.haNodeID = fmt.Sprintf("%s-%s", hostname, self.Listen)

	// Register or update current node
	node := &ha.ClusterNode{
		ID:        self.haNodeID,
		Name:      hostname,
		Host:      self.IP,
		Port:      0, // Will be parsed from Listen
		Role:      "primary",
		Status:    "online",
		LastPing:  time.Now(),
		IsEnabled: true,
	}

	// Parse port from Listen address
	if _, portStr, err := net.SplitHostPort(self.Listen); err == nil {
		if port, err := fmt.Sscanf(portStr, "%d", &node.Port); port != 1 || err != nil {
			node.Port = 8080
		}
	}

	// Try to create the node; if it already exists, update it
	if err := self.haSvc.AddNode(context.Background(), node); err != nil {
		// Node may already exist, try updating
		if existing, err := self.haSvc.GetNode(context.Background(), self.haNodeID); err == nil {
			existing.Status = "online"
			existing.LastPing = time.Now()
			existing.IsEnabled = true
			self.haSvc.UpdateNode(context.Background(), existing)
		}
	}
	logrus.Infof("[webserver.go::initHA] registered node %s as online", self.haNodeID)

	// Start heartbeat goroutine
	haCtx, cancel := context.WithCancel(context.Background())
	self.haCancel = cancel
	go self.haHeartbeat(haCtx)
}

// haHeartbeat periodically updates the node's last ping time and participates in leader election.
func (self *WebServer) haHeartbeat(ctx context.Context) {
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()
	var isLeader bool

	for {
		select {
		case <-ctx.Done():
			if isLeader {
				if err := self.haSvc.Resign(context.Background(), self.haNodeID); err != nil {
					logrus.Errorf("[webserver.go::haHeartbeat] failed to resign: %v", err)
				}
			}
			return
		case <-ticker.C:
			node, err := self.haSvc.GetNode(ctx, self.haNodeID)
			if err != nil {
				logrus.Errorf("[webserver.go::haHeartbeat] failed to get node: %v", err)
				continue
			}
			node.LastPing = time.Now()
			node.Status = "online"
			if err := self.haSvc.UpdateNode(ctx, node); err != nil {
				logrus.Errorf("[webserver.go::haHeartbeat] failed to update node: %v", err)
			}

			if self.redisClient != nil {
				becameLeader, err := self.haSvc.ElectLeader(ctx, self.haNodeID)
				if err != nil {
					logrus.Errorf("[webserver.go::haHeartbeat] leader election failed: %v", err)
					isLeader = false
					continue
				}
				if becameLeader && !isLeader {
					logrus.Infof("[webserver.go::haHeartbeat] node %s became leader", self.haNodeID)
				} else if !becameLeader && isLeader {
					logrus.Warnf("[webserver.go::haHeartbeat] node %s lost leader status", self.haNodeID)
				}
				isLeader = becameLeader
			}
		}
	}
}

// shutdownHA marks the current node as offline and stops the heartbeat goroutine.
func (self *WebServer) shutdownHA() {
	if self.haCancel != nil {
		self.haCancel()
	}
	if self.haSvc != nil && self.haNodeID != "" {
		node, err := self.haSvc.GetNode(context.Background(), self.haNodeID)
		if err == nil {
			node.Status = "offline"
			node.LastPing = time.Now()
			self.haSvc.UpdateNode(context.Background(), node)
			logrus.Infof("[webserver.go::shutdownHA] marked node %s as offline", self.haNodeID)
		}
	}
}

func (self *WebServer) IsDuplicate(err error) bool {
	if err == nil {
		return false
	}

	orm := self.orm
	switch orm.DriverName() {
	case "sqlite3", "sqlite":
		// modernc.org/sqlite error checking
		errStr := err.Error()
		// Check for constraint violation in error message
		// modernc.org/sqlite format: "constraint failed: UNIQUE constraint failed: table.column (2067)"
		if strings.Contains(errStr, "constraint failed") &&
			(strings.Contains(errStr, "UNIQUE constraint") ||
				strings.Contains(errStr, "PRIMARY KEY constraint") ||
				strings.Contains(errStr, "FOREIGN KEY constraint")) {
			return true
		}
		// Also check the error code if available
		// modernc.org/sqlite Error type has Code() method
		if sqliteErr, ok := err.(interface{ Code() int }); ok {
			code := sqliteErr.Code()
			// SQLITE_CONSTRAINT = 19, extended codes include 2067 (UNIQUE), etc.
			if code == 19 || code >= 2067 && code <= 2099 {
				return true
			}
		}
	case "mysql":
		e := err.(*mysql.MySQLError)
		if e.Number == 1062 || e.Number == 1169 || e.Number == 1022 {
			return true
		}
	}
	return false
}

func (self *WebServer) ResetPassword(user, password string) error {
	if isWeakPass(password) {
		return fmt.Errorf("Password(%v) too weak!", password)
	}

	orm := self.orm
	session := orm.NewSession()
	defer session.Close()

	_, err := session.Where(`role = ?`, roleSuper).Cols("pass").
		Update(&models.TblUser{
			Pass: makePassword(password),
		})
	return err
}

// triggerWorkflows finds workflows matching the given interaction and enqueues
// their enabled actions into the async workflow queue for execution.
func (self *WebServer) triggerWorkflows(interaction *v2models.Interaction) {
	if self.workflowQueue == nil || self.workflowSvc == nil {
		return
	}

	// Find enabled workflows that match this interaction
	workflows, err := self.workflowSvc.ListWorkflows("", boolPtr(true), 1, 100)
	if err != nil {
		logrus.Errorf("[webserver.go::triggerWorkflows] ListWorkflows: %v", err)
		return
	}

	for _, wf := range workflows.Items {
		// Exclude response-type actions from async queue; they are
		// handled synchronously by the web handler (checkWorkflowResponse).
		var otherActions v2models.Actions
		for _, a := range wf.Actions {
			if a.Type != v2models.ActionTypeResponse {
				otherActions = append(otherActions, a)
			}
		}
		if len(otherActions) == 0 {
			continue
		}
		if err := self.workflowQueue.EnqueueWorkflow(wf.ID, otherActions, interaction); err != nil {
			logrus.Errorf("[webserver.go::triggerWorkflows] EnqueueWorkflow %s: %v", wf.ID, err)
		}
	}
}

// boolPtr returns a pointer to the given bool value
func boolPtr(v bool) *bool {
	return &v
}
